define(["require", "exports", "react", "ting"], function (require, exports, React, ting_1) {
    "use strict";
    var btnStyle = { marginRight: "10px" };
    return function () { return React.createElement("article", null,
        React.createElement("h2", null, "\u5747\u5300\u5206\u914D"),
        React.createElement(ting_1.Row, null,
            React.createElement(ting_1.Col, null,
                React.createElement("div", { className: "bg-info" }, "1")),
            React.createElement(ting_1.Col, null,
                React.createElement("div", { className: "bg-warn" }, "2")),
            React.createElement(ting_1.Col, null,
                React.createElement("div", { className: "bg-info" }, "3")),
            React.createElement(ting_1.Col, null,
                React.createElement("div", { className: "bg-warn" }, "4"))),
        React.createElement("h2", null, "\u5E26\u95F4\u9699\u5747\u5300\u5206\u914D"),
        React.createElement(ting_1.Row, { gutter: 20 },
            React.createElement(ting_1.Col, null,
                React.createElement("div", { className: "bg-primary" }, "1")),
            React.createElement(ting_1.Col, null,
                React.createElement("div", { className: "bg-success" }, "2")),
            React.createElement(ting_1.Col, null,
                React.createElement("div", { className: "bg-primary" }, "3")),
            React.createElement(ting_1.Col, { span: 2 },
                React.createElement("div", { className: "bg-success" }, "4"))),
        React.createElement(ting_1.Row, { gutter: 20 },
            React.createElement(ting_1.Col, null,
                React.createElement("div", { className: "bg-primary" }, "1")),
            React.createElement(ting_1.Col, null,
                React.createElement("div", { className: "bg-success" }, "2")),
            React.createElement(ting_1.Col, null,
                React.createElement("div", { className: "bg-primary" }, "3")),
            React.createElement(ting_1.Col, null,
                React.createElement("div", { className: "bg-success" }, "4")),
            React.createElement(ting_1.Col, null,
                React.createElement("div", { className: "bg-primary" }, "5"))),
        React.createElement("h2", null, "12\u7B49\u5206"),
        React.createElement(ting_1.Row, { cols: 12 },
            React.createElement(ting_1.Col, { span: 3 },
                React.createElement("div", { className: "bg-primary" }, "1")),
            React.createElement(ting_1.Col, { span: 3 },
                React.createElement("div", { className: "bg-success" }, "2")),
            React.createElement(ting_1.Col, { span: 3 },
                React.createElement("div", { className: "bg-primary" }, "3")),
            React.createElement(ting_1.Col, { span: 3 },
                React.createElement("div", { className: "bg-success" }, "4"))),
        React.createElement(ting_1.Row, { cols: 12 },
            React.createElement(ting_1.Col, { span: 3 },
                React.createElement("div", { className: "bg-primary" }, "1")),
            React.createElement(ting_1.Col, { span: 3 },
                React.createElement("div", { className: "bg-success" }, "2")),
            React.createElement(ting_1.Col, { span: 6 },
                React.createElement("div", { className: "bg-primary" }, "3"))),
        React.createElement("h2", null, "\u5E26\u95F4\u969912\u7B49\u5206"),
        React.createElement(ting_1.Row, { cols: 12, gutter: 20 },
            React.createElement(ting_1.Col, { span: 3 },
                React.createElement("div", { className: "bg-primary box-mbxs" }, "1")),
            React.createElement(ting_1.Col, { span: 3 },
                React.createElement("div", { className: "bg-success box-mbxs" }, "2")),
            React.createElement(ting_1.Col, { span: 3 },
                React.createElement("div", { className: "bg-primary box-mbxs" }, "3")),
            React.createElement(ting_1.Col, { span: 3 },
                React.createElement("div", { className: "bg-success box-mbxs" }, "4"))),
        React.createElement(ting_1.Row, { cols: 12, gutter: 20 },
            React.createElement(ting_1.Col, { span: 3 },
                React.createElement("div", { className: "bg-primary" }, "1")),
            React.createElement(ting_1.Col, { span: 3 },
                React.createElement("div", { className: "bg-success" }, "2")),
            React.createElement(ting_1.Col, { span: 6 },
                React.createElement("div", { className: "bg-primary" }, "3"))),
        React.createElement("h2", null, "\u8D85\u51FA\u81EA\u52A8\u6362\u884C"),
        React.createElement(ting_1.Row, { cols: 12, gutter: 20 },
            React.createElement(ting_1.Col, { span: 6 },
                React.createElement("div", { className: "bg-primary box-mbxs" },
                    "1",
                    React.createElement("br", null),
                    "1")),
            React.createElement(ting_1.Col, { span: 6 },
                React.createElement("div", { className: "bg-success box-mbxs" }, "2")),
            React.createElement(ting_1.Col, { span: 6 },
                React.createElement("div", { className: "bg-primary box-mbxs" }, "3")),
            React.createElement(ting_1.Col, { span: 6 },
                React.createElement("div", { className: "bg-success box-mbxs" }, "4")),
            React.createElement(ting_1.Col, { span: 6 },
                React.createElement("div", { className: "bg-primary box-mbxs" }, "5")),
            React.createElement(ting_1.Col, { span: 6 },
                React.createElement("div", { className: "bg-success box-mbxs" }, "6")),
            React.createElement(ting_1.Col, { span: 6 },
                React.createElement("div", { className: "bg-primary box-mbxs" }, "7")),
            React.createElement(ting_1.Col, { span: 6 },
                React.createElement("div", { className: "bg-success box-mbxs" }, "8")))); };
});
