define(["require", "exports", "react", "ting"], function (require, exports, React, ting_1) {
    "use strict";
    return function () { return React.createElement("article", null,
        React.createElement("h2", null, "\u5B57\u4F53\u56FE\u6807"),
        React.createElement(ting_1.Icon, { size: 32 }, "\uF000"),
        React.createElement(ting_1.Icon, { size: 32 }, "\uF001"),
        React.createElement(ting_1.Icon, { size: 48 }, "\uF002"),
        React.createElement("h2", null, "twitter emoji"),
        React.createElement(ting_1.Icon, { size: 72 }, "\uD83D\uDCDD"),
        React.createElement(ting_1.Icon, { size: 72 }, "\uD83D\uDCD6"),
        React.createElement(ting_1.Icon, { size: 72 }, "\uD83D\uDCF7"),
        React.createElement(ting_1.Icon, { size: 72 }, "\u26F7"),
        React.createElement(ting_1.Icon, { size: 72 }, "\uD83C\uDF5F"),
        React.createElement("h2", null, "\u56FE\u7247\u56FE\u6807"),
        React.createElement(ting_1.Icon, { size: 72, src: "https://cdn.bootcss.com/twemoji/11.2.0/2/72x72/1f649.png" }),
        React.createElement(ting_1.Icon, { size: 72, src: "/linsk1998/ting/master/images/logo.png" }),
        React.createElement(ting_1.Icon, { size: 72, png: "https://cdn.bootcss.com/twemoji/11.2.0/2/72x72/1f649.png" }),
        React.createElement(ting_1.Icon, { size: 72, png: "/linsk1998/ting/master/images/logo.png" }),
        React.createElement("h2", null, "SVG\u4F18\u96C5\u964D\u7EA7"),
        React.createElement(ting_1.Icon, { size: 144, svg: "https://cdn.bootcss.com/twemoji/11.2.0/2/svg/1f649.svg", png: "https://cdn.bootcss.com/twemoji/11.2.0/2/72x72/1f649.png" }),
        React.createElement(ting_1.Icon, { size: 144, png: "https://cdn.bootcss.com/twemoji/11.2.0/2/72x72/1f649.png" }),
        React.createElement("h2", null, "\u52A8\u56FE\u4F18\u96C5\u964D\u7EA7"),
        React.createElement(ting_1.Icon, { size: 144, atsvg: "/linsk1998/spinfox/master/spinfox.svg", apng: "/linsk1998/spinfox/master/spinfox.png", awebp: "/linsk1998/spinfox/master/spinfox.webp", hfpsgif: "/linsk1998/spinfox/master/spinfox.hfps.gif", gif: "/linsk1998/spinfox/master/spinfox.gif" }),
        React.createElement(ting_1.Icon, { size: 144, apng: "/linsk1998/spinfox/master/spinfox.png", awebp: "/linsk1998/spinfox/master/spinfox.webp", hfpsgif: "/linsk1998/spinfox/master/spinfox.hfps.gif", gif: "/linsk1998/spinfox/master/spinfox.gif" }),
        React.createElement(ting_1.Icon, { size: 144, awebp: "/linsk1998/spinfox/master/spinfox.webp", hfpsgif: "/linsk1998/spinfox/master/spinfox.hfps.gif", gif: "/linsk1998/spinfox/master/spinfox.gif" }),
        React.createElement(ting_1.Icon, { size: 144, hfpsgif: "/linsk1998/spinfox/master/spinfox.hfps.gif", gif: "/linsk1998/spinfox/master/spinfox.gif" }),
        React.createElement(ting_1.Icon, { size: 144, gif: "/linsk1998/spinfox/master/spinfox.gif" })); };
});
