define(["require", "exports", "react", "ting"], function (require, exports, React, ting_1) {
    "use strict";
    return function () {
        return React.createElement(ting_1.Layout, null,
            React.createElement(ting_1.Header, null,
                React.createElement("ul", { className: "nav nav-tabs" },
                    React.createElement(ting_1.NavItem, { path: "/aaa", activeClassName: "active", index: true },
                        React.createElement("li", null,
                            React.createElement(ting_1.NavLink, { to: "aaa" }, "aaa"))),
                    React.createElement(ting_1.NavItem, { path: "/bbb", activeClassName: "active" },
                        React.createElement("li", null,
                            React.createElement(ting_1.NavLink, { to: "bbb" }, "bbb"))),
                    React.createElement(ting_1.NavItem, { path: "/ccc", activeClassName: "active" },
                        React.createElement("li", null,
                            React.createElement(ting_1.NavLink, { to: "ccc" }, "ccc"))))),
            React.createElement(ting_1.Content, null,
                React.createElement(ting_1.Switch, null,
                    React.createElement(ting_1.IndexRoute, { path: "/aaa" },
                        React.createElement(ting_1.Layout, null,
                            React.createElement(ting_1.Sider, null,
                                React.createElement("ul", { className: "nav nav-tabs tabs-stacked" },
                                    React.createElement(ting_1.NavItem, { path: "/aaa", activeClassName: "active", index: true },
                                        React.createElement("li", null,
                                            React.createElement(ting_1.NavLink, { to: "aaa" }, "aaa"))),
                                    React.createElement(ting_1.NavItem, { path: "/bbb", activeClassName: "active" },
                                        React.createElement("li", null,
                                            React.createElement(ting_1.NavLink, { to: "bbb" }, "abb"))),
                                    React.createElement(ting_1.NavItem, { path: "/ccc", activeClassName: "active" },
                                        React.createElement("li", null,
                                            React.createElement(ting_1.NavLink, { to: "ccc" }, "acc"))))),
                            React.createElement(ting_1.Content, null,
                                React.createElement(ting_1.Switch, null,
                                    React.createElement(ting_1.IndexRoute, { path: "/aaa" },
                                        React.createElement(ting_1.Layout, null,
                                            React.createElement(ting_1.Header, null,
                                                React.createElement("ul", { className: "nav nav-tabs box-mbmd" },
                                                    React.createElement(ting_1.NavItem, { path: "/aaa", activeClassName: "active", index: true },
                                                        React.createElement("li", null,
                                                            React.createElement(ting_1.NavLink, { to: "aaa" }, "aaa"))),
                                                    React.createElement(ting_1.NavItem, { path: "/bbb", activeClassName: "active" },
                                                        React.createElement("li", null,
                                                            React.createElement(ting_1.NavLink, { to: "bbb" }, "aab"))),
                                                    React.createElement(ting_1.NavItem, { path: "/ccc", activeClassName: "active" },
                                                        React.createElement("li", null,
                                                            React.createElement(ting_1.NavLink, { to: "ccc" }, "aac"))))),
                                            React.createElement(ting_1.Content, null,
                                                React.createElement(ting_1.Switch, null,
                                                    React.createElement(ting_1.IndexRoute, { path: "/aaa" }, "aaa"),
                                                    React.createElement(ting_1.Route, { path: "/bbb" }, "aab"),
                                                    React.createElement(ting_1.Route, { path: "/ccc" }, "aac"))))),
                                    React.createElement(ting_1.Route, { path: "/bbb" }, "abb"),
                                    React.createElement(ting_1.Route, { path: "/ccc" }, "acc"))))),
                    React.createElement(ting_1.Route, { path: "/bbb" }, "bbb"),
                    React.createElement(ting_1.Route, { path: "/ccc" }, "ccc"))));
    };
});
